name: lan_scanner
description: Dart / Flutter package that allows discovering network devices via multi-threaded ICMP pings.
version: 3.5.0
homepage: https://github.com/ivirtex/lan_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_ping: ^7.0.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  import_sorter: ^4.6.0
  test: ^1.20.2
  very_good_analysis: ^3.0.1
